"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dbg@+3s-#^pvg$j!*wigdwx@#f5xky3ng(p*8)#$swrywc27%8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'leads',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL = 'leads.User'
TIME_ZONE = 'Asia/Kolkata'

import os

# ---- Database: SQLite for quick starts, PostgreSQL via DB_ENGINE=postgres (DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT)
if os.environ.get('DB_ENGINE') == 'postgres':
    DATABASES = {'default': {
        'ENGINE': 'django.db.backends.postgresql', 'NAME': os.environ.get('DB_NAME', 'crm'), 'USER': os.environ.get('DB_USER', 'crm'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''), 'HOST': os.environ.get('DB_HOST', 'localhost'), 'PORT': os.environ.get('DB_PORT', '5432'),
    }}

# ---- Public addresses. Redirect URIs registered in Meta/Google are PUBLIC_BASE_URL + /api/connections/<platform>/callback
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', 'http://localhost:3100').rstrip('/')
FRONTEND_URL = os.environ.get('FRONTEND_URL', PUBLIC_BASE_URL).rstrip('/')

# ---- Token encryption (Fernet keys, comma separated for rotation). Generate: python -c "from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())"
CRM_ENCRYPTION_KEY = os.environ.get('CRM_ENCRYPTION_KEY', '')

# ---- Meta (Facebook + Instagram) app. Create it at developers.facebook.com
META_APP_ID = os.environ.get('META_APP_ID', '')
META_APP_SECRET = os.environ.get('META_APP_SECRET', '')
META_GRAPH_VERSION = os.environ.get('META_GRAPH_VERSION', 'v25.0')  # check the current version in Meta's changelog
META_SCOPES = os.environ.get('META_SCOPES', 'leads_retrieval,pages_show_list,pages_read_engagement,pages_manage_metadata,ads_read,business_management').split(',')
META_LOGIN_CONFIG_ID = os.environ.get('META_LOGIN_CONFIG_ID', '')  # set to use "Facebook Login for Business" instead of plain scopes
META_VERIFY_TOKEN = os.environ.get('META_VERIFY_TOKEN', '')  # app-level webhook handshake (Meta dashboard → Webhooks)
META_PAGE_TOKEN = os.environ.get('META_PAGE_TOKEN', '')  # only for the manual website-style Meta webhook

# ---- Google Ads. Cloud project + OAuth client at console.cloud.google.com, developer token from a Google Ads manager account
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_DEVELOPER_TOKEN = os.environ.get('GOOGLE_DEVELOPER_TOKEN', '')
GOOGLE_LOGIN_CUSTOMER_ID = os.environ.get('GOOGLE_LOGIN_CUSTOMER_ID', '')  # manager (MCC) account id, only if you access clients through one
GOOGLE_ADS_API_VERSION = os.environ.get('GOOGLE_ADS_API_VERSION', 'v22')

# Fake Meta/Google servers for trying the whole flow without real credentials. NEVER enable in production.
AD_PLATFORMS_MOCK = os.environ.get('AD_PLATFORMS_MOCK') == '1'
