# Generated by Django 6.1.1 on 2026-10-06 11:04

import django.db.models.deletion
import django.utils.timezone
import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('website', 'Website form'), ('meta', 'Meta Ads'), ('google', 'Google Ads')], max_length=10)),
                ('token', models.CharField(default=leads.models._token, max_length=60, unique=True)),
                ('secret', models.CharField(default=leads.models._secret, max_length=40)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=240)),
                ('leads', models.CharField(blank=True, max_length=120)),
                ('test', models.BooleanField(default=False)),
                ('payload', models.TextField(blank=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='leads.webhook')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
