# Generated by Django 6.1.1 on 2026-10-06 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_webhook_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AdConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta Ads'), ('google', 'Google Ads')], max_length=10, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=60)),
                ('account_name', models.CharField(blank=True, max_length=160)),
                ('business_id', models.CharField(blank=True, max_length=60)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('access_token_enc', models.TextField(blank=True)),
                ('refresh_token_enc', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=14)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_count', models.PositiveIntegerField(default=0)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
